### ISSUE TITLE
Can not running the code

### ISSUE THREAD

**Issue by Abambres01** [edgjj/Pulverizer#1]
Hi, could you guide me how to run your code? 
![image](https://user-images.githubusercontent.com/90351940/139515603-8c120234-dc00-45fd-92f8-5eb9285ec688.png)

**Comment by edgjj** [comment]
Hey! At this moment, building is kinda broken as it uses weird relative paths.

To fix that you need to replace `#include "../Kraps/processor/processor.hpp"` in pulverizer_single.hpp with `#include "../../Kraps/processor/processor.hpp"`. 

Then, hopefully, build will succeed (if not - check if you have Kraps cloned), after that just copy Pulverizer.vst3 from `Builds\VisualStudio2019\x64\(BuildType)\VST3` to system VST3 path and it's ready to run with any VST3-capable host.

**Comment by Abambres01** [comment]
Ok, thanks I will try
